USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/huawei/y210/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true

TARGET_BOARD_PLATFORM := msm7k
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := y210
TARGET_OTA_ASSERT_DEVICE := y210,hwy210

# Audio
# BOARD_PROVIDES_LIBAUDIO := true

# TARGET_PROVIDES_LIBLIGHTS := true

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := y210

TARGET_SPECIFIC_HEADER_PATH := device/huawei/y210/include

#recovery
BOARD_LDPI_RECOVERY := true
BOARD_HAS_JANKY_BACKBUFFER := true
BOARD_CUSTOM_GRAPHICS           := ../../../device/huawei/y210/recovery/graphics.c


# OpenGL drivers config file path
BOARD_EGL_CFG := device/huawei/y210/prebuilt/system/lib/egl/egl.cfg
BOARD_USES_QCOM_HARDWARE := true
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE
BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_LIBS := true
COMMON_GLOBAL_CFLAGS += -DTARGET_MSM7x27A -DTARGET_MSM7x27
TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true

WITH_JIT := true
ENABLE_JSC_JIT := true
JS_ENGINE := v8
HTTP := chrome

BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true

# RIL
# BOARD_PROVIDES_LIBRIL := true

# Wi-Fi
BOARD_WPA_SUPPLICANT_DRIVER := WEXT
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_ath6kl
BOARD_WLAN_DEVICE           := ar6000
WIFI_DRIVER_MODULE_PATH     := /system/wifi/ar6000.ko
WIFI_DRIVER_MODULE_ARG      := ""
WIFI_DRIVER_MODULE_NAME     := ar6000
WPA_SUPPLICANT_VERSION      := VER_0_8_X
WIFI_PRE_LOADER             := wlan_detect

# Partition sizes from device /proc/mtd (bytes)
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00500000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0BA00000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0A000000
BOARD_CACHEIMAGE_PARTITION_SIZE := 0x03A00000
BOARD_FLASH_BLOCK_SIZE := 131072

# Kernel 
# TARGET_KERNEL_SOURCE := kernel/huawei/y210
# TARGET_KERNEL_CONFIG := cyanogen_y210_defconfig
BOARD_KERNEL_CMDLINE := console=ttyDCC0 androidboot.hardware=huawei
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096

TARGET_PREBUILT_KERNEL := device/huawei/y210/kernel

TARGET_RECOVERY_INITRC := device/huawei/y210/recovery/etc/init.rc
# BOARD_DATA_DEVICE := /dev/block/mmcblk0p13
# BOARD_DATA_FILESYSTEM := ext4
# BOARD_DATA_FILESYSTEM_OPTIONS := rw
# BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p12
# BOARD_SYSTEM_FILESYSTEM := ext4
# BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
# BOARD_CACHE_DEVICE := /dev/block/mmcblk0p6
# BOARD_CACHE_FILESYSTEM := ext4
# BOARD_CACHE_FILESYSTEM_OPTIONS := rw
# BOARD_USES_MMCUTILS := true
# BOARD_HAS_NO_MISC_PARTITION := true

BOARD_USE_USB_MASS_STORAGE_SWITCH := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/usb_mass_storage/lun
TARGET_USE_CUSTOM_SECOND_LUN_NUM := 2
BOARD_VOLD_MAX_PARTITIONS := 19
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
BOARD_UMS_LUNFILE := "/sys/devices/platform/usb_mass_storage/lun0/file"
